#!/usr/bin/env bash
# Setting up UFW firewall with essential rules for a web server

# Install UFW (Uncomplicated Firewall)
sudo apt install -y ufw

# Set default policies: allow all outgoing traffic,
#  deny all incoming traffic
sudo ufw default allow outgoing
sudo ufw default deny incoming

# Allow SSH (port 22) to enable remote access
sudo ufw allow 22

# Allow HTTPS (port 443) for secure web traffic
sudo ufw allow 443

# Allow HTTP (port 80) for regular web traffic
sudo ufw allow 80

# Enable the firewall with the defined rules
echo "y" | sudo ufw enable
